spring:
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

#    defer-datasource-initialization: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/airbnb?&characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
    password: team-15
logging:
  level:
    org.hibernate.SQL: debug
    team15:
      airbnb: debug
